data: Cora # Cora, Pubmed, CS, Photo, Computers, flickr

num_epoch: 200 # 500 
batch_size: 64
lr: !!float 1e-3
weight_decay: !!float 0.0001
num_neighbors: [-1] #[25, 10]
device: 'cuda:0'
seed: 2025

eval_per_epochs: 5
save_model_intervals: 20

hidden_size: 512

experiment_name: ''
ablation: '' # 'no-M_A', 'no-M_X', 'no-M'
